//
// Created by Ding Cheng DONG on 21/05/2025 A.
//

#ifndef HANDY_ANDROID_HACK_THIS_EMULATOR_DETECTION_H
#define HANDY_ANDROID_HACK_THIS_EMULATOR_DETECTION_H

#endif //HANDY_ANDROID_HACK_THIS_EMULATOR_DETECTION_H

bool isEmulator();