//
// Created by Ding Cheng DONG on 16/05/2025 A.
//

#ifndef HANDY_ANDROID_HACK_THIS_FRIDA_FUNCTION_HOOK_DETECTION_H
#define HANDY_ANDROID_HACK_THIS_FRIDA_FUNCTION_HOOK_DETECTION_H

#endif //HANDY_ANDROID_HACK_THIS_FRIDA_FUNCTION_HOOK_DETECTION_H

bool check_inlinehook();